export const MOCK_GAMES = [
  { id: 'elden-ring', title: 'Elden Ring', developer: 'FromSoftware', publisher: 'Bandai Namco', year: 2022, genres: ['RPG', 'Action', 'Souls-like'], platforms: ['PC', 'PS5', 'Xbox Series X', 'PS4'], synopsis: 'Um vasto mundo aberto repleto de mistérios, chefes brutais e uma lore profunda criada por Hidetaka Miyazaki e George R.R. Martin. Explore o Entre-Terra em busca dos fragmentos do Anel Dourado.', cover: 'https://picsum.photos/seed/eldenring/400/560', communityRating: 4.8, trending: true },
  { id: 'god-of-war', title: 'God of War: Ragnarök', developer: 'Santa Monica Studio', publisher: 'Sony', year: 2022, genres: ['Action', 'Adventure', 'RPG'], platforms: ['PS5', 'PS4'], synopsis: 'Kratos e Atreus enfrentam o Ragnarök enquanto percorrem os Nove Reinos da mitologia nórdica. Uma épica história de pai e filho com batalhas inesquecíveis e emoções profundas.', cover: 'https://picsum.photos/seed/godofwar/400/560', communityRating: 4.9, trending: true },
  { id: 'cyberpunk', title: 'Cyberpunk 2077', developer: 'CD Projekt Red', publisher: 'CD Projekt', year: 2020, genres: ['RPG', 'Action', 'Open World'], platforms: ['PC', 'PS5', 'Xbox Series X', 'PS4'], synopsis: 'Seja V, um mercenário em Night City. Com Johnny Silverhand em sua mente, navegue por uma megalópole cyberpunk repleta de escolhas, perigo e identidade.', cover: 'https://picsum.photos/seed/cyberpunk2077/400/560', communityRating: 4.2, trending: true },
  { id: 'hollow-knight', title: 'Hollow Knight', developer: 'Team Cherry', publisher: 'Team Cherry', year: 2017, genres: ['Metroidvania', 'Platformer', 'Action'], platforms: ['PC', 'Nintendo Switch', 'PS4', 'Xbox One'], synopsis: 'Explore um vasto reino subterrâneo de insetos e heróis. Descubra os segredos de Hallownest em uma aventura repleta de arte artesanal e trilha sonora cativante.', cover: 'https://picsum.photos/seed/hollowknight/400/560', communityRating: 4.7, trending: false },
  { id: 'hades', title: 'Hades', developer: 'Supergiant Games', publisher: 'Supergiant Games', year: 2020, genres: ['Roguelite', 'Action', 'Dungeon Crawler'], platforms: ['PC', 'Nintendo Switch', 'PS5', 'Xbox'], synopsis: 'Desafie o deus da morte enquanto luta para escapar do Submundo grego. Cada tentativa revela mais da história e aprofunda os relacionamentos com deuses olímpicos.', cover: 'https://picsum.photos/seed/hades2020/400/560', communityRating: 4.8, trending: true },
  { id: 'witcher3', title: 'The Witcher 3: Wild Hunt', developer: 'CD Projekt Red', publisher: 'CD Projekt', year: 2015, genres: ['RPG', 'Open World', 'Adventure'], platforms: ['PC', 'PS5', 'PS4', 'Xbox', 'Nintendo Switch'], synopsis: 'Geralt de Rívia busca sua filha adotiva enquanto a Caçada Selvagem ameaça o mundo. Um RPG monumental com centenas de horas de conteúdo e escolhas que importam.', cover: 'https://picsum.photos/seed/witcher3game/400/560', communityRating: 4.9, trending: false },
  { id: 'rdr2', title: 'Red Dead Redemption 2', developer: 'Rockstar Games', publisher: 'Rockstar Games', year: 2018, genres: ['Action', 'Adventure', 'Open World'], platforms: ['PC', 'PS4', 'Xbox One'], synopsis: 'A história de Arthur Morgan e a gangue Van der Linde no oeste americano em declínio. Uma obra-prima narrativa com o mundo aberto mais detalhado já criado.', cover: 'https://picsum.photos/seed/rdr2game/400/560', communityRating: 4.9, trending: false },
  { id: 'sekiro', title: 'Sekiro: Shadows Die Twice', developer: 'FromSoftware', publisher: 'Activision', year: 2019, genres: ['Action', 'Souls-like', 'Stealth'], platforms: ['PC', 'PS4', 'Xbox One'], synopsis: 'Como Lobo, o shinobi de um braço só, navegue pelo Japão feudal em busca de vingança. Combate preciso e brutal com mecânicas únicas de postura e contra-ataque.', cover: 'https://picsum.photos/seed/sekirogame/400/560', communityRating: 4.7, trending: false },
  { id: 'spiderman2', title: "Marvel's Spider-Man 2", developer: 'Insomniac Games', publisher: 'Sony', year: 2023, genres: ['Action', 'Adventure', 'Superhero'], platforms: ['PS5'], synopsis: 'Peter Parker e Miles Morales enfrentam Kraven e o simbionte Venom em Nova York. Dobro de heróis, dobro de ação em uma aventura visualmente deslumbrante.', cover: 'https://picsum.photos/seed/spiderman2ps5/400/560', communityRating: 4.6, trending: true },
  { id: 'celeste', title: 'Celeste', developer: 'Maddy Makes Games', publisher: 'Maddy Makes Games', year: 2018, genres: ['Platformer', 'Indie', 'Puzzle'], platforms: ['PC', 'Nintendo Switch', 'PS4', 'Xbox One'], synopsis: 'Ajude Madeline a sobreviver na escalada da Montanha Celeste enquanto enfrenta seus próprios demônios internos. Plataforma precisa com uma história tocante sobre saúde mental.', cover: 'https://picsum.photos/seed/celestegame/400/560', communityRating: 4.8, trending: false },
  { id: 'outer-wilds', title: 'Outer Wilds', developer: 'Mobius Digital', publisher: 'Annapurna Interactive', year: 2019, genres: ['Adventure', 'Exploration', 'Puzzle'], platforms: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch'], synopsis: 'Explore um sistema solar preso em loop de 22 minutos. Um dos jogos mais originais já criados, onde o conhecimento é sua única arma em uma aventura de descoberta cósmica.', cover: 'https://picsum.photos/seed/outerwildsgame/400/560', communityRating: 4.9, trending: false },
  { id: 'baldurs-gate3', title: "Baldur's Gate 3", developer: 'Larian Studios', publisher: 'Larian Studios', year: 2023, genres: ['RPG', 'Strategy', 'Turn-based'], platforms: ['PC', 'PS5', 'Xbox Series X'], synopsis: 'Com um parasita mind flayer em seu cérebro, explore Faerûn com um grupo de companheiros improváveis. O RPG mais ambicioso de nossa geração com liberdade quase infinita.', cover: 'https://picsum.photos/seed/baldursgate/400/560', communityRating: 4.9, trending: true },
  { id: 'ghost-tsushima', title: 'Ghost of Tsushima', developer: 'Sucker Punch Productions', publisher: 'Sony', year: 2020, genres: ['Action', 'Adventure', 'Open World'], platforms: ['PS5', 'PS4'], synopsis: 'Jin Sakai torna-se o Fantasma para defender Tsushima da invasão mongol. Um tributo deslumbrante ao cinema de samurai com um dos mundos mais belos dos games.', cover: 'https://picsum.photos/seed/ghosttsushima/400/560', communityRating: 4.7, trending: false },
  { id: 'disco-elysium', title: 'Disco Elysium', developer: 'ZA/UM', publisher: 'ZA/UM', year: 2019, genres: ['RPG', 'Detective', 'Narrative'], platforms: ['PC', 'PS5', 'PS4', 'Xbox'], synopsis: 'Um detetive com amnésia investiga um assassinato em uma cidade portuária em crise. RPG de diálogo puro com uma das escritas mais inteligentes da história dos games.', cover: 'https://picsum.photos/seed/discoelysium/400/560', communityRating: 4.8, trending: false },
  { id: 'last-of-us', title: 'The Last of Us Part I', developer: 'Naughty Dog', publisher: 'Sony', year: 2013, genres: ['Action', 'Adventure', 'Survival'], platforms: ['PS5', 'PS4', 'PC'], synopsis: 'Joel escolta Ellie através de um Estados Unidos pós-apocalíptico. Uma das histórias mais poderosas e emotivas já contadas em forma de jogo.', cover: 'https://picsum.photos/seed/lastofusgame/400/560', communityRating: 4.9, trending: true },
  { id: 'returnal', title: 'Returnal', developer: 'Housemarque', publisher: 'Sony', year: 2021, genres: ['Roguelike', 'Action', 'Shooter'], platforms: ['PS5', 'PC'], synopsis: 'Selene está presa em loop mortal num planeta alienígena hostil. Um roguelike brutal e viciante com combate frenético e uma narrativa psicológica perturbadora.', cover: 'https://picsum.photos/seed/returnalgame/400/560', communityRating: 4.5, trending: false },
  { id: 'stardew', title: 'Stardew Valley', developer: 'ConcernedApe', publisher: 'ConcernedApe', year: 2016, genres: ['Simulation', 'RPG', 'Farming'], platforms: ['PC', 'Nintendo Switch', 'PS4', 'Xbox One', 'Mobile'], synopsis: 'Herde a fazenda do seu avô e construa uma nova vida no Valley. Um dos jogos indie mais amados de todos os tempos com profundidade surpreendente e charme infinito.', cover: 'https://picsum.photos/seed/stardewvalley/400/560', communityRating: 4.8, trending: false },
  { id: 'dark-souls3', title: 'Dark Souls III', developer: 'FromSoftware', publisher: 'Bandai Namco', year: 2016, genres: ['Action', 'RPG', 'Souls-like'], platforms: ['PC', 'PS4', 'Xbox One'], synopsis: 'A Chama está a se extinguir. Como o Campeão das Cinzas, reúna os Lordes em épicas batalhas. O clímax da trilogia Souls com inimigos e chefes icônicos.', cover: 'https://picsum.photos/seed/darksouls3/400/560', communityRating: 4.7, trending: false },
  { id: 'minecraft', title: 'Minecraft', developer: 'Mojang Studios', publisher: 'Microsoft', year: 2011, genres: ['Sandbox', 'Survival', 'Creative'], platforms: ['PC', 'Mobile', 'PS4', 'Xbox', 'Nintendo Switch'], synopsis: 'O jogo que não precisa de apresentação. Construa, explore e sobreviva num mundo gerado por procedimentos. O jogo mais vendido da história com criatividade sem limites.', cover: 'https://picsum.photos/seed/minecraftgame/400/560', communityRating: 4.6, trending: false },
  { id: 'ori', title: 'Ori and the Will of the Wisps', developer: 'Moon Studios', publisher: 'Xbox Game Studios', year: 2020, genres: ['Platformer', 'Metroidvania', 'Indie'], platforms: ['PC', 'Xbox One', 'Nintendo Switch'], synopsis: 'Ori continua sua jornada numa nova floresta repleta de perigos. Um dos jogos mais belos visualmente com gameplay fluido, trilha orquestral e história emocionante.', cover: 'https://picsum.photos/seed/oriwisp/400/560', communityRating: 4.8, trending: false },
];

export const ALL_GENRES = [...new Set(MOCK_GAMES.flatMap(g => g.genres))].sort();
export const ALL_YEARS = [...new Set(MOCK_GAMES.map(g => g.year))].sort((a, b) => b - a);
export const ALL_DEVELOPERS = [...new Set(MOCK_GAMES.map(g => g.developer))].sort();
export const TRENDING_GAMES = MOCK_GAMES.filter(g => g.trending);